server:
  port: 8080
  tomcat:
      uri-encoding: UTF-8

spring:
  http:
      encoding:
          force: true
          charset: UTF-8
          enabled: true

  messages:
      encoding: UTF-8
  thymeleaf:
      prefix: classpath:/templates/
      suffic: .html
      mode: HTML5
      encoding: UTF-8

  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@139.196.88.74:1521:orcl
      username: ddcmrp
      password: ddcmrp

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

